In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [2]:
df1 = pd.read_csv("datascience_df2.csv")
df2 = pd.read_csv("levelup_df3.csv")
df3= pd.read_csv("towards_datascience2.csv")
combine_df = pd.concat([df1,df2,df3])
combine_df.head()

Unnamed: 0                                              title        date  \
0           0  Mitigating Ethical Risks in Generative AI: Str...  2024-01-03   
1           1                          DSC Weekly 2 January 2024  2024-01-02   
2           2  Mastering IoT Data Management for Business Suc...  2024-01-01   
3           3  Generative AI business model disruption: The N...  2024-01-01   
4           4  GenAI: Synthesizing DNA Sequences with LLM Tec...  2024-01-01   

                                            SubTitle  
0  Artificial Intelligence (AI) has been around f...  
1                 Announcements Top Stories In-Depth  
2  In today’s tech-driven landscape, the prolifer...  
3  2024 will be all about changing business model...  
4  When people talk about Large Language Models, ...

In [3]:
combine_df['text'] = combine_df['title'] + combine_df['SubTitle']
combine_df.head()

Unnamed: 0                                              title        date  \
0           0  Mitigating Ethical Risks in Generative AI: Str...  2024-01-03   
1           1                          DSC Weekly 2 January 2024  2024-01-02   
2           2  Mastering IoT Data Management for Business Suc...  2024-01-01   
3           3  Generative AI business model disruption: The N...  2024-01-01   
4           4  GenAI: Synthesizing DNA Sequences with LLM Tec...  2024-01-01   

                                            SubTitle  \
0  Artificial Intelligence (AI) has been around f...   
1                 Announcements Top Stories In-Depth   
2  In today’s tech-driven landscape, the prolifer...   
3  2024 will be all about changing business model...   
4  When people talk about Large Language Models, ...   

                                                text  
0  Mitigating Ethical Risks in Generative AI: Str...  
1  DSC Weekly 2 January 2024Announcements Top Sto...  
2  Mastering IoT Data Management for Business Suc...  
3  Generative AI business model disruption: The N...  
4  GenAI: Synthesizing DNA Sequences with LLM Tec...

In [4]:
combine_df.drop(columns=["Unnamed: 0"],inplace=True)

In [31]:
combine_df2 = combine_df.copy()

In [32]:
combine_df2.head()

title        date  \
0  Mitigating Ethical Risks in Generative AI: Str...  2024-01-03   
1                          DSC Weekly 2 January 2024  2024-01-02   
2  Mastering IoT Data Management for Business Suc...  2024-01-01   
3  Generative AI business model disruption: The N...  2024-01-01   
4  GenAI: Synthesizing DNA Sequences with LLM Tec...  2024-01-01   

                                            SubTitle  \
0  Artificial Intelligence (AI) has been around f...   
1                 Announcements Top Stories In-Depth   
2  In today’s tech-driven landscape, the prolifer...   
3  2024 will be all about changing business model...   
4  When people talk about Large Language Models, ...   

                                                text  
0  Mitigating Ethical Risks in Generative AI: Str...  
1  DSC Weekly 2 January 2024Announcements Top Sto...  
2  Mastering IoT Data Management for Business Suc...  
3  Generative AI business model disruption: The N...  
4  GenAI: Synthesizing DNA Sequences with LLM Tec...

In [7]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Chesta\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [8]:
from nltk.stem import WordNetLemmatizer

In [9]:
STOPWORDS = set(stopwords.words('english'))

In [10]:
def simple_clean_text(x):
    x = x.lower()
    x = re.sub('[^a-z]'," ",x)
    x = re.sub(' +',' ',x).strip()
    words = x.split()
    
    lemmatizer = WordNetLemmatizer()
    words =[lemmatizer.lemmatize(i) for i in words]

    words = [w for w in words if w not in STOPWORDS]
        
        
    return " ".join(words)

In [11]:
combine_df2['text'] = combine_df2['text'].apply(lambda x: simple_clean_text(x))

In [12]:
combine_df2.head()

title        date  \
0  Mitigating Ethical Risks in Generative AI: Str...  2024-01-03   
1                          DSC Weekly 2 January 2024  2024-01-02   
2  Mastering IoT Data Management for Business Suc...  2024-01-01   
3  Generative AI business model disruption: The N...  2024-01-01   
4  GenAI: Synthesizing DNA Sequences with LLM Tec...  2024-01-01   

                                            SubTitle  \
0  Artificial Intelligence (AI) has been around f...   
1                 Announcements Top Stories In-Depth   
2  In today’s tech-driven landscape, the prolifer...   
3  2024 will be all about changing business model...   
4  When people talk about Large Language Models, ...   

                                                text  
0  mitigating ethical risk generative ai strategy...  
1    dsc weekly january announcement top story depth  
2  mastering iot data management business success...  
3  generative ai business model disruption nyt la...  
4  genai synthesizing dna sequence llm techniques...

# TfIDF : Term Frequency Inverse Document Frequency

This is quite confusing but let's try to break and undertsand how it is relevant in our context of text generation in am ore heuristic approach.

This helps in identifying the keywords by by taking into account not only how many times a given word **t** occurs in a given **document** but how frequently it does occur in other documents as well.

Majorly uses for text retrival as well as text mining that helps in automatic detection of the keywords.

The algorithm does use .three numerical characteristics:-

* number of time tf(t,d) that word t occurs in a document d, this number is known as **term frequency**

* the total number **N** of documents in a given corpus D

* number of documents df(t) which contains the given term t; this number is known as **document frequency**.

Based on last two characteristic swe do get the **idf** N/df(t)

Keywords characterizing the given document d we select words t with the largest value of product tf-idf(t,d,D) = tf(t,d). idf(t,D)

This leads to adequate selection of the keywords.

Here the model will assign each occurrence of word t in the corpus randomly assigned to one of the N documents in the corpus. The probability of single occurrence of t to a specific document will be 1/N; why because there are N documents and we are assigning equal probability.

Probability estimation is under random assignment model a specific document d ends up with exactly k occurrences of word t.

n = tf(t,D) total number of times t appear in the entire corpus.
k = tf(t,d) number of times t appear in the document.

This is in realtionship with the **Tf-IDF** and Keyword Importance
Significance of word is determined via not just frequency of word in that document but also how unique that word is across the entire corpus.

Words that are common across many documents are deemed less but words which are frequent in few documents are copnsidered more important.

Why we are using this probablistic approach is to think Tf-IDF in a manner where we are thinking about randomness of the word distribution and to assess the importance of words in the documents based on the likelihood of their distribution pattern.

Linking the paper that help you to understand the concept of TF-IDF in a detailed way 

https://www.tandfonline.com/doi/full/10.1080/03081079.2017.1291635

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [14]:
vectorizer = TfidfVectorizer()
tfidf_mat = vectorizer.fit_transform(combine_df2['text'].values)
tfidf_mat.shape

(560, 2559)

In [15]:
query = "artificial intelligence"

* TF-IDF has been chosen to find the keywords for each document present in the corpus.

Now to generate the text of the given query; we'll be taking the advantage of Cosine Similarity that helps in determine how similar two documenst are to each other.

Basic Concepts

**Vector Space Model** : - text is going to be represented in a vector space. Value in each dimension represents the importance or frquency of that word in the text.

**Word Vectors** :- For individual words, vector representation like Glove, Word2Vec are often used. these vectors capture semantic meanings of words based on their context in a large corpus.

#### Cosine Similarity

* Measures the cosine of angle between two non-zero vectors in a multi-dimensional space. We calculate it in terms of **dot** product of vectors divided by product of their magnitude.

* It helps us to quantify how similar they are in terms of their semantic meanings.

**Interpret the Results**

* Cosine similarity of 1 means vectors are identical
* Cosine similarity of -1 is they are completely dissimilar
* Cosine similarity of 0 means there is no significant similarity between the two.



In [16]:


# Vectorize the titles using TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(combine_df2['text'])  # Assuming 'title' is the column name

# Function to find similar titles based on a query
def find_similar_titles(query, top_n=5):
    query_tfidf = tfidf_vectorizer.transform([query])
    cos_similarities = cosine_similarity(query_tfidf, tfidf_matrix).flatten()
    similar_indices = cos_similarities.argsort()[-top_n:][::-1]
    
    similar_titles = combine_df2['text'].iloc[similar_indices]
    return similar_titles

# Example Query
query = "ai models"  # Replace with your query
similar_titles = find_similar_titles(query)
print("Titles similar to the query:", similar_titles)


Titles similar to the query: 0      mitigating ethical risk generative ai strategy...
16     ai justice brave new world part ai governancei...
182    gen ai framework tool every ai ml engineer kno...
214    google gemini ai v chatgpt ai deep dive titan ...
8      creating fair prosperous brave new world ai su...
Name: text, dtype: object


In [3]:
# !pip install gensim

In [33]:
def simple_clean_text(x):
    x = x.lower()
    x = re.sub('[^a-z]'," ",x)
    x = re.sub(' +',' ',x).strip()
    words = x.split()
    
    lemmatizer = WordNetLemmatizer()
    words =[lemmatizer.lemmatize(i) for i in words]

    words = [w for w in words if w not in STOPWORDS]
        
        
    return (words)

In [35]:
combine_df2['text'] = combine_df2['text'].apply(lambda x: simple_clean_text(x))

In [38]:
from gensim.models.word2vec import Word2Vec

#create the model

word2vec_model = Word2Vec(min_count=0,workers=8,vector_size=15)

#prepare the vocab

word2vec_model.build_vocab(combine_df2['text'].values)

#train the model

word2vec_model.train(combine_df2['text'].values,total_examples=word2vec_model.corpus_count,epochs=30)


(176785, 189840)

In [39]:
vocabulary_sample = list(word2vec_model.wv.index_to_key[:5])

In [40]:
vector_sample = [word2vec_model.wv[word] for word in vocabulary_sample]
vector_sample

[array([-1.1178092 ,  0.06370014,  2.3720043 , -2.6711257 , -0.10399573,
         0.7032753 ,  0.05867551,  1.3012085 ,  0.2515336 ,  0.9431123 ,
         3.541885  ,  1.3180712 ,  0.6709672 , -1.1814612 , -3.017418  ],
       dtype=float32),
 array([-0.9594652 ,  0.15246652,  1.963687  , -2.4227076 , -0.07080292,
         0.7337299 ,  0.00429893,  1.0033599 ,  0.18997736,  0.9089392 ,
         2.948596  ,  1.0328969 ,  0.73770064, -1.0407968 , -2.5568447 ],
       dtype=float32),
 array([-0.99132276,  0.06777174,  1.9525964 , -2.3286557 , -0.02881214,
         0.7018621 ,  0.10257982,  0.9631509 ,  0.19499597,  0.75778484,
         2.747382  ,  1.1561697 ,  0.5004294 , -1.0920178 , -2.4527543 ],
       dtype=float32),
 array([-6.8087125e-01,  7.5712259e-04,  1.7312801e+00, -1.8385310e+00,
         1.0245566e-01,  4.0995201e-01,  4.6106651e-02,  8.2870197e-01,
         2.4044864e-01,  8.7641740e-01,  2.4217796e+00,  9.9158388e-01,
         4.5506853e-01, -9.3280286e-01, -1.9519191e+00]

In [41]:
vocabulary_sample, vector_sample[:1]

(['data', 'ai', 'guide', 'part', 'learning'],
 [array([-1.1178092 ,  0.06370014,  2.3720043 , -2.6711257 , -0.10399573,
          0.7032753 ,  0.05867551,  1.3012085 ,  0.2515336 ,  0.9431123 ,
          3.541885  ,  1.3180712 ,  0.6709672 , -1.1814612 , -3.017418  ],
        dtype=float32)])

In [42]:
model_wv_contents = {
    "Vocabulary Size": len(word2vec_model.wv),
    "Sample Words": word2vec_model.wv.index_to_key[:10],  # First 10 words in the vocabulary
    "Vector for a Sample Word ('data')": word2vec_model.wv['data'] if 'data' in word2vec_model.wv else "Not in Vocabulary"
}

model_wv_contents

{'Vocabulary Size': 2573,
 'Sample Words': ['data',
  'ai',
  'guide',
  'part',
  'learning',
  'using',
  'model',
  'python',
  'code',
  'llm'],
 "Vector for a Sample Word ('data')": array([-1.1178092 ,  0.06370014,  2.3720043 , -2.6711257 , -0.10399573,
         0.7032753 ,  0.05867551,  1.3012085 ,  0.2515336 ,  0.9431123 ,
         3.541885  ,  1.3180712 ,  0.6709672 , -1.1814612 , -3.017418  ],
       dtype=float32)}

In [43]:
query_sentence = "machine learning trends"

In [44]:
words = query_sentence.split()
words

['machine', 'learning', 'trends']

In [77]:
def average_vector(sentence,model):
    words = sentence.split()
    # print(words)

    word_vectors = [model.wv[word] for word in words if word in model.wv]

    if len(word_vectors)==0:
        return np.zeros(model.vector_size)
    else:
        return np.mean(word_vectors,axis=0)

In [78]:
query_vector = average_vector(query_sentence,word2vec_model)

In [79]:
query_vector.shape

(15,)

In [80]:
title_vectors = [average_vector(" ".join(row), word2vec_model) for row in combine_df2.text]

In [73]:
(title_vectors[0][0])

0.021957703

In [81]:
similarities =[cosine_similarity([query_vector], [title_vector])[0][0] for title_vector in title_vectors]

In [85]:
titles_with_similarities = list(zip(combine_df2['text'],similarities))

In [87]:
sorted_titles = sorted(titles_with_similarities,key=lambda x: x[1],reverse=True)

In [106]:
for title in range(len(sorted_titles[:5])):
    print(f'{" ".join(sorted_titles[title][0])}: {(sorted_titles[title][1])}')



understanding machine learning paradigm comparative study supervised unsupervised algorithmsintroduction: 0.9997289776802063
machine learning need case study signature detectionthe need insight: 0.9997285604476929
boosting algorithm machine learning part adaboostyou throw data scientist: 0.9997137188911438
title mastering unit test python part mock mocker quick great tool want leave: 0.9996119737625122
learning discrete data harmonium part essentialsunderstanding logic behind adaboost: 0.9995943903923035
